sudo: required

before_install:
    - apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - apt-add-repository -y ppa:beineri/opt-qt542
    - apt-get -qq update
    - apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54serialport
    - PATH="/opt/qt54/bin:$PATH"
    - qt54-env.sh 

install:
    - wget 'https://sourceforge.net/projects/astyle/files/latest/download'
    - tar -zxvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

script: 
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc | grep Formatted)"
    - qmake
    - make

language: cpp

