name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: run EpsilonDashboardSetup
      run: ./EpsilonDashboardSetup.sh
    
    - run: conan user -p solarcarAction1 -r epsilon action
    - run: conan config set general.revisions_enabled=1
    
    - name: Creating build folder
      run: mkdir build && cd build
    
    - name: checking file directory
      run: ls ../
    - name: install package with conan
      run: conan install ../Epsilon-Dashboard --build=missing
    - name: qmake
      run: qmake ../Epsilon-Dashboard/src/
    - run: make
    - run: make check
